<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-MREH9ID" failures="1" tests="5" name="Test" time="38.934" errors="0" timestamp="2025-01-24T17:00:05 IST">
  <testcase classname="tests.FourTest" name="testFour" time="0.016"/>
  <testcase classname="tests.TwoTest" name="testTwo" time="0.002"/>
  <testcase classname="tests.ThreeTest" name="testThree" time="0.001"/>
  <testcase classname="tests.LoginTest" name="login" time="15.057">
    <failure type="java.lang.AssertionError" message="expected [Success] but found [Failure]">
      <![CDATA[java.lang.AssertionError: expected [Success] but found [Failure]
at tests.LoginTest.login(LoginTest.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="tests.LoginTest" name="login" time="14.919"/>
</testsuite> <!-- Test -->
